[Server]
Mode = "debug"
Addr = "0.0.0.0:8080"
ReadTimeout = 60
WriteTimeout = 60

[Database]
Dialect = "postgresql"
Host = "postgresql"
User = "gorm"
Password = "gorm"
DBName = "gin_blog"
Port = "5432"
SSLMode = "disable"
TimeZone = "Asia/Shanghai"